# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/charlock_holmes/all/charlock_holmes.rbi
#
# charlock_holmes-0.7.7

class CharlockHolmes::EncodingDetector
  def binary_scan_length; end
  def binary_scan_length=(arg0); end
  def detect(*arg0); end
  def detect_all(*arg0); end
  def initialize(scan_len = nil); end
  def is_binary?(arg0); end
  def self.build_encoding_table; end
  def self.detect(str, hint_enc = nil); end
  def self.detect_all(str, hint_enc = nil); end
  def self.encoding_table; end
  def self.supported_encodings; end
  def strip_tags; end
  def strip_tags=(arg0); end
  def strip_tags?; end
end
class CharlockHolmes::Converter
  def self.convert(arg0, arg1, arg2); end
end
class CharlockHolmes::Transliterator
  def self.id_list; end
  def self.transliterate(arg0, arg1); end
end
module CharlockHolmes
end
