# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/i18n_data/all/i18n_data.rbi
#
# i18n_data-0.7.0

module I18nData
  def self.countries(language_code = nil); end
  def self.country_code(name); end
  def self.data_provider; end
  def self.data_provider=(provider); end
  def self.fetch(*args); end
  def self.language_code(name); end
  def self.languages(language_code = nil); end
  def self.normal_to_region_code(normal); end
  def self.recognise_code(type, search); end
end
class I18nData::BaseException < StandardError
  def to_s; end
end
class I18nData::NoTranslationAvailable < I18nData::BaseException
end
class I18nData::AccessDenied < I18nData::BaseException
end
class I18nData::Unknown < I18nData::BaseException
end
