# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby_rncryptor` gem.
# Please instead update this file by running `bin/tapioca gem ruby_rncryptor`.

# source://ruby_rncryptor//lib/ruby_rncryptor.rb#9
class RubyRNCryptor
  include ::OpenSSL

  class << self
    # source://ruby_rncryptor//lib/ruby_rncryptor.rb#12
    def decrypt(data, password); end

    # source://ruby_rncryptor//lib/ruby_rncryptor.rb#47
    def encrypt(data, password, version = T.unsafe(nil)); end

    # From http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/PKCS5.html#module-OpenSSL::PKCS5-label-Important+Note+on+Checking+Passwords
    #
    # source://ruby_rncryptor//lib/ruby_rncryptor.rb#80
    def eql_time_cmp(a, b); end

    # source://ruby_rncryptor//lib/ruby_rncryptor.rb#72
    def truncate_multibyte_password(str); end
  end
end
