# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-json` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-json`.

# source://simplecov-json//lib/simplecov-json.rb#4
class SimpleCov::Formatter::JSONFormatter
  # source://simplecov-json//lib/simplecov-json.rb#6
  def format(result); end

  # source://simplecov-json//lib/simplecov-json.rb#44
  def output_filename; end

  # source://simplecov-json//lib/simplecov-json.rb#48
  def output_filepath; end

  # source://simplecov-json//lib/simplecov-json.rb#52
  def output_message(result); end

  private

  # source://simplecov-json//lib/simplecov-json.rb#58
  def output_path; end
end
