# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/stub_server/all/stub_server.rbi
#
# stub_server-0.4.0

class StubServer
  def boot; end
  def call(env); end
  def initialize(port, replies, ssl: nil, json: nil, webrick: nil); end
  def self.open(port, replies, **options); end
  def shutdown; end
  def wait; end
end
