# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/workato-connector-sdk/all/workato-connector-sdk.rbi
#
# workato-connector-sdk-1.0.1

module Workato
end
module Workato::Testing
end
class Workato::Testing::VCRMultipartBodyMatcher
  def self.call(request1, request2); end
  def self.multipart_request?(content_type); end
  def self.normalized_multipart_body(request); end
end
