inherit_from: ./.rubocop_todo.yml

require:
  - rubocop-sorbet
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.6
  NewCops: enable
  SuggestExtensions: false

Metrics/ParameterLists:
  Description: Avoid parameter lists longer than three or four parameters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#too-many-params
  Enabled: false
  Max: 5
  CountKeywordArgs: true

Naming/FileName:
  Exclude:
    - lib/workato-connector-sdk.rb

Metrics/MethodLength:
  Max: 30
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - workato-connector-sdk.gemspec
    - spec/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*

Style/IfUnlessModifier:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/AbcSize:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/MissingRespondToMissing:
  Exclude:
    - lib/workato/connector/sdk/request.rb

Style/RescueModifier:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Sorbet/FalseSigil:
  Exclude:
    - spec/fixtures/connectors/workbot3000.rb

RSpec/NamedSubject:
  EnforcedStyle: named_only

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

# False positive massive alerts
RSpec/RepeatedExample:
  Exclude:
    - 'spec/workato/extension/object_spec.rb'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/examples/lookup_table/connector_spec.rb'
    - 'spec/workato/connector/sdk/account_properties_spec.rb'
    - 'spec/workato/connector/sdk/lookup_tables_spec.rb'
    - 'spec/workato/connector/sdk/workato_schemas_spec.rb'

RSpec/ExpectInHook:
  Exclude:
    - 'spec/examples/authorized_connection/connector_spec.rb'
    - 'spec/examples/oauth_refresh_automatic/connector_spec.rb'
    - 'spec/examples/oauth_refresh_manual/connector_spec.rb'
