name: Ruby

on: [push]

jobs:
  rspec:

    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: test
      BUNDLE_WITHOUT: development
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: '2.7'
          - ruby-version: '3.0'
          - ruby-version: '3.1'
          - ruby-version: '3.2'
          - ruby-version: '3.2'
            gemfile: gemfiles/Gemfile.activesupport-7.0

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}

      - name: Run tests
        run: bundle exec rspec
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
